---
title: "bosker2014"
author: "Catherine Maximous"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

[No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information. You will likely contact the authors of the original study, so this should be professional and forward facing. It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  

## Introduction

	The adaptive control hypothesis proposes that distinct social environments or contexts may impose different demands on how a speaker regulates their language use (Green & Abutalebi, 2013). For example, speakers can differ in their language processing and how they manage their cognitive resources according to their interactional context. This refers to the context of language use that plays a role in mediating how a bilingual regulates the use of their two languages. This framework has often been used to explain how variations across bilingual populations arise and how these variations are important for understanding how language processing is shaped by the context of the speaker. These research interests are the motivation to explore further what other factors are shaped by a bilingual speaker or other speakers’ interactional context.  For this project proposal, I would like to further explore how predictive processing in a listening task may reveal further how a speakers’ environment plays a role in their language processing. Predictive processing examines how a hearer makes a strong set of expectations about incoming linguistic input. In Bosker et al. (2014), they examined how native Dutch speakers use disfluencies when uttered by a native or a non-native speaker to predict a low-referent item followed by the disfluency. Disfluencies can be defined as filled pauses such as “um” or “uh” in a sentence that may cue the listener to various things. In the paper, Bosker and colleagues used a visual world paradigm to test whether the Dutch speakers’ predictive processing differed based on whether they heard a native or a non-native accent during a disfluency. They found that in native speech, disfluencies may signal that a low-frequent or more difficult word is coming which aids listeners in predicting these low-frequency items. This effect was however not found in non-native speech. When the Dutch speakers heard an accented speech, they no longer reliably used the speaker as a cue to predict the low-frequent items. This suggests that predictive strategies are adaptive and that listeners do not treat all speakers the same. However, the environment that Dutch speakers live and speak their languages in, may differ greatly from the one that speakers in California live in. Therefore, it would be interesting to see whether asking the same research questions and sampling from California may render different results from what Bosker and colleagues have found.


## Methods

To conduct this experiment, I will implement the reaction time portion of the visual world paradigm. However, due to the paper being in Dutch, I will not be able to use any of their audios or materials as the participant pool on SONA may not have that many native Dutch speakers for data collection. Instead, I will open the participant pool to anyone that identifies as a Native English speaker, but may be bilingual with a second language as well. In Bosker et al. (2014), they presented their participants with a set of 30 low frequency words and 30 high frequency words from Severens, Lommel, Ratinckx, and Hartsuiker (2005). Then a native Dutch speaker and a non-native Dutch speaker recorded audio material that instructs the participants to “Click on the [target]" as well as the same sentences but with the disfluency “Click on the uh [target].” To conduct my experiment, I will implement Experiment 2 with accented speech and record 30 sentences with disfluencies and low frequency items as well as 30 sentences without disfluencies and high frequency items. This will be a 4 picture design, where participants will hear the instructions and click on the item. To measure predictive processing, I will be looking at the participants’ mouth clicks as a measure of reaction time to when they heard a disfluency with a low frequency item versus a high frequency item. I will calculate them according to the paper which used the mouth clicks at target onset for correct trials only. 

The challenges that I may face in conducting this experiment is ensuring that all my materials are properly made and coded into JsPsych. I will first have a volunteer record the first half of the sentence “Click on” and “Click on uh”  then I will cut from the start of click to the beginning of “the” then record all sentences again but with all the items as “the [target].” Then I will splice the target nouns (start of the) onto the disfluent and fluent sentence. This will all be done in Praat and ensure that both the disfluent and fluent sentences only differ in the presence of “uh.” For my target nouns and pictures, I will use the same list of items and picture bank listed in the paper. I can also compare their high frequency and low frequency for English speakers using a normed list of pictures and items for English by Adams and colleagues (2024) normed English stimuli. This paper shows a very complex experiment with different parts including eye-tracking, however for the purpose of this class, I would like to focus on experiment 2 and implement it behavioral to look at mouth clicks as a measure of reaction time when hearing a disfluency or a non-disfluent sentence in what is perceived as a non-native English accent. 


### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
